version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: milanomilano
      POSTGRES_DB: test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - 5001:5000
    environment:
      DATABASE_URL: postgres://postgres:milanomilano@postgres:5432/test