version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: test
#  backend:
#    build: .
#    ports:
#      - 5000:5000
#    environment:
#      PORT: 5000