name: Build and Deploy
on: push
env:
  IMAGE_NAME: <IMAGE_NAME>
  GCLOUD_PROJECT_ID: <PROJECT_NAME>
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push Docker images
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: _json_key
          password: ${{ secrets.GCR_JSON }}
          registry: asia.gcr.io
          image_name: <PROJECT_ID>/<IMAGE_NAME>
          push_git_tag: true
      - name: Secret Injector
        run: |
          echo "LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }}" >> key.env && \
          echo -e "\nLINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}" >> key.env
      # https://github.com/marketplace/actions/cloud-run
      - name: cloudrun
        uses: hackinteach/action-cloud-run@v1.0
        with:
          image: asia.gcr.io/<PROJECT_ID>/<IMAGE_NAME>
          service: linebot
          project: <PROJECT_ID>
          region: asia-southeast1
          env: key.env
          service key: ${{ secrets.CLOUDRUN_SA }} # base64-encoded